---
- hosts: all
  become: true
  pre_tasks:
    - name: Install updates (Debian)
      tags: always, yannick
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_os_family == 'Debian'
      ignore_errors: yes

    - name: Install updates (RedHat)
      tags: always
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_os_family == 'RedHat'
      ignore_errors: yes
- hosts: all
  become: true
  roles:
    - base

- hosts: container_servers
  become: true
  roles:
    - container_servers

- hosts: linode_servers
  become: true
  roles:
    - linode_servers
