---

- hosts: all
  tasks:

    - name: Create a user account
      ansible.builtin.user:
        name: dana
        groups: dev
        shell: /bin/bash
        comment: The best one
        state: present      


